server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  sensitive-headers: Cookie,Set-Cookie
  host:
    time-to-live: -1
    connect-timeout-millis: 60000
    max-per-route-connections: 10000
    max-total-connections: 5000
  routes:
    sensitiveHeaders: Cookie,Set-Cookie
    department:
      path: /department/**
      serviceId: department-service
    employee:
      path: /employee/**
      serviceId: employee-service
    organization:
      path: /organization/**
      serviceId: organization-service
    auth:
#      sensitiveHeaders: Cookie,Set-Cookie
      path: /uaa/**
      serviceId: auth-service

gateway:
  cors:
    allowed-origins: '*'
    allowed-methods: 'GET,HEAD,POST,PUT,DELETE,OPTIONS,PATCH'
    allowed-headers: '*'
    exposed-headers: 'Content-Type,Authorization,Content-Length,X-Requested-With,Link,X-Total-Count'
    allow-credentials: true
    max-age: 3600

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000

app:
  jwt:
    secret: 5d66670787ff43778785318f5a12f8c0
    avlPeriod: 24h # 24h
    header: Authorization
    tokenPrefix: Bearer