server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  host:
    time-to-live: -1
    connect-timeout-millis: 60000
    max-per-route-connections: 10000
    max-total-connections: 5000
  routes:
    department:
      path: /department/**
      serviceId: department-service
    employee:
      path: /employee/**
      serviceId: employee-service
    organization:
      path: /organization/**
      serviceId: organization-service
    auth:
      path: /uaa/**
      serviceId: auth-service

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000

app:
  jwt:
    secret: 5d66670787ff43778785318f5a12f8c0
    avlPeriod: 24h # 24h
    header: Authorization
    tokenPrefix: Bearer