server:
  port: 8060

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8061/eureka/

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  ignoredServices: '*'
    host:
      time-to-live: -1
      connect-timeout-millis: 60000
      max-per-route-connections: 60000
      max-total-connections: 5000
      socket-timeout-millis: 60000
  routes:
    auth-service:
      path: /uaa/** #path that will be intercepted
      url: auth-service #which url the request will e mapped to
      stripPrefix: false #if zuul should replace the "/uaa/" segment
      sensitiveHeaders:
    department:
      path: /department/**
      serviceId: department-service
      stripPrefix: false
      sensitiveHeaders:
    employee:
      path: /employee/**
      serviceId: employee-service
      stripPrefix: false
      sensitiveHeaders:
    organization:
      path: /organization/**
      serviceId: organization-service
      stripPrefix: false
      sensitiveHeaders: