#This configuration file will hold common configs to be shared among all files
spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
      sampler:
        probability: 1.0

eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/ #where our registry server is located

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8060/gw-created-by-syphan/uaa/api/v1/users/current #which uri will be used to find the user
      token-info-uri: http://localhost:8060/gw-created-by-syphan/uaa/oauth/check_token #add this information

logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000


ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000