#This configuration file will hold common configs to be shared among all files
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
  output.ansi.enabled: ALWAYS

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8060/gw-created-by-syphan/uaa/api/v1/users/current #which uri will be used to find the user
      token-info-uri: http://localhost:8060/gw-created-by-syphan/uaa/oauth/check_token #add this information

logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000


ribbon:
  ConnectTimeout: 20000
  ReadTimeout: 20000